import Link from "next/link";

export const metadata = {
  title: "Terms of Service — Conduikt",
  description: "The terms governing your use of the Conduikt platform.",
  alternates: { canonical: "https://conduikt.com/terms/" },
};

export default function TermsPage() {
  const lastUpdated = "February 18, 2026";

  return (
    <div className="mx-auto w-full max-w-[1200px] px-4 pb-20 pt-16 md:px-10 md:pt-24">
        {/* Header */}
        <div className="mb-12 max-w-[760px] border-b border-line pb-8">
          <p className="mb-4 text-label text-accent">Legal</p>
          <h1 className="mb-3 text-display-m text-text">Terms of service</h1>
          <p className="text-body-s text-text-3">Last updated: {lastUpdated}</p>
        </div>

        <div className="prose-conduikt">

          <section>
            <h2>1. Acceptance of terms</h2>
            <p>
              By creating an account or using Conduikt (the &quot;Service&quot;), you agree
              to be bound by these Terms of Service. If you do not agree, do not use
              the Service. These terms apply to all users including individuals and
              organisations.
            </p>
          </section>

          <section>
            <h2>2. Description of service</h2>
            <p>
              Conduikt is an AI-powered marketing automation platform that helps users
              generate content, conduct SEO audits, and manage marketing assets.
              The Service is operated by Technicity Digital, Lagos, Nigeria.
            </p>
          </section>

          <section>
            <h2>3. Accounts</h2>
            <ul className="list-disc">
              <li>You must provide accurate and complete information when creating an account.</li>
              <li>You are responsible for maintaining the security of your account credentials.</li>
              <li>You must be at least 18 years old to use the Service.</li>
              <li>One person or legal entity may not maintain more than one free account.</li>
              <li>You are responsible for all activity that occurs under your account.</li>
            </ul>
          </section>

          <section>
            <h2>4. Acceptable use</h2>
            <p>You agree not to use Conduikt to:</p>
            <ul className="list-disc">
              <li>Generate spam, misleading content, or content that violates third-party rights</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Attempt to reverse-engineer, scrape, or exploit the platform</li>
              <li>Impersonate any person or entity</li>
              <li>Interfere with the security or integrity of the Service</li>
            </ul>
            <p>
              We reserve the right to suspend or terminate accounts that violate these
              terms without prior notice.
            </p>
          </section>

          <section>
            <h2>5. Payment and subscriptions</h2>
            <ul className="list-disc">
              <li>Paid plans are billed as described on our pricing page.</li>
              <li>All payments are processed by Lemon Squeezy. By purchasing, you agree to their terms.</li>
              <li>Prices are in USD and exclusive of applicable taxes.</li>
              <li>We do not offer refunds except where required by applicable law.</li>
              <li>We reserve the right to change pricing with 30 days&apos; notice to existing subscribers.</li>
            </ul>
          </section>

          <section>
            <h2>6. AI-generated content</h2>
            <p>
              Content generated by Conduikt&apos;s AI features is provided as-is for
              informational and creative purposes. You are responsible for reviewing
              and verifying AI-generated content before publishing it. We do not
              guarantee the accuracy, completeness, or suitability of AI outputs.
              You own the content you generate through the platform.
            </p>
          </section>

          <section>
            <h2>7. Intellectual property</h2>
            <p>
              The Conduikt platform, including its design, code, and branding, is
              owned by Technicity Digital. You retain ownership of content you create
              using the Service. By using the Service, you grant us a limited licence
              to process your content solely to provide the Service to you.
            </p>
          </section>

          <section>
            <h2>8. Availability and service changes</h2>
            <p>
              We strive for high availability but do not guarantee uninterrupted
              access. We may modify, suspend, or discontinue features of the Service
              at any time. We will provide reasonable notice for significant changes
              that affect paid subscribers.
            </p>
          </section>

          <section>
            <h2>9. Limitation of liability</h2>
            <p>
              To the maximum extent permitted by law, Technicity Digital shall not be
              liable for any indirect, incidental, special, consequential, or punitive
              damages arising from your use of Conduikt. Our total liability to you
              shall not exceed the amount you paid us in the 12 months preceding the
              claim.
            </p>
          </section>

          <section>
            <h2>10. Termination</h2>
            <p>
              You may cancel your account at any time from your account settings.
              We may terminate or suspend your account immediately for breach of these
              terms. Upon termination, your right to use the Service ceases and we
              may delete your data after a 30-day grace period.
            </p>
          </section>

          <section>
            <h2>11. Governing law</h2>
            <p>
              These terms are governed by the laws of the Federal Republic of Nigeria.
              Any disputes shall be resolved in the courts of Lagos State, Nigeria.
            </p>
          </section>

          <section>
            <h2>12. Contact</h2>
            <p>
              Questions about these terms? Contact us at{" "}
              <a
                href="mailto:hello@conduikt.com"
              >
                hello@conduikt.com
              </a>
              .
            </p>
          </section>
        </div>

      <div className="mt-16 flex flex-wrap items-center justify-between gap-4 border-t border-line pt-8 text-body-s text-text-3">
        <span>© {new Date().getFullYear()} Conduikt · Technicity Digital</span>
        <Link href="/privacy" className="hover-link hover:text-text">
          Privacy policy
        </Link>
      </div>
    </div>
  );
}
