import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  Image,
  StyleSheet,
} from "@react-pdf/renderer";

const colors = {
  surface0: "#0C0C0E",
  surface1: "#141418",
  surface2: "#1C1C22",
  accent: "#D9663A",
  textPrimary: "#E8E4DE",
  textSecondary: "#9B958C",
  textTertiary: "#5E5A54",
  success: "#6B9E78",
  warning: "#C9A84C",
  white: "#FFFFFF",
};

const styles = StyleSheet.create({
  page: {
    backgroundColor: colors.surface0,
    padding: 40,
    fontFamily: "Helvetica",
    color: colors.textPrimary,
  },
  coverPage: {
    backgroundColor: colors.surface0,
    padding: 60,
    fontFamily: "Helvetica",
    color: colors.textPrimary,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  brandMark: {
    width: 48,
    height: 48,
    backgroundColor: colors.accent,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 40,
  },
  brandLetter: {
    color: colors.surface0,
    fontSize: 24,
    fontWeight: "bold",
  },
  coverTitle: {
    fontSize: 32,
    fontWeight: "bold",
    color: colors.textPrimary,
    marginBottom: 8,
  },
  coverSubtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 40,
  },
  metaRow: {
    flexDirection: "row",
    marginBottom: 6,
  },
  metaLabel: {
    fontSize: 10,
    color: colors.textTertiary,
    width: 120,
    textTransform: "uppercase" as const,
    letterSpacing: 0.5,
  },
  metaValue: {
    fontSize: 10,
    color: colors.textSecondary,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.accent,
    marginBottom: 16,
    marginTop: 8,
  },
  statRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 20,
  },
  statCard: {
    backgroundColor: colors.surface1,
    borderRadius: 8,
    padding: 14,
    width: "30%",
  },
  statLabel: {
    fontSize: 9,
    color: colors.textTertiary,
    textTransform: "uppercase" as const,
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  statValue: {
    fontSize: 22,
    fontWeight: "bold",
    color: colors.textPrimary,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: colors.surface2,
    borderRadius: 4,
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginBottom: 4,
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.surface2,
  },
  tableCell: {
    fontSize: 9,
    color: colors.textSecondary,
  },
  tableHeaderCell: {
    fontSize: 8,
    color: colors.textTertiary,
    textTransform: "uppercase" as const,
    letterSpacing: 0.5,
    fontWeight: "bold",
  },
  priorityItem: {
    backgroundColor: colors.surface1,
    borderRadius: 6,
    padding: 12,
    marginBottom: 6,
    borderLeftWidth: 3,
    borderLeftColor: colors.accent,
  },
  priorityTitle: {
    fontSize: 11,
    fontWeight: "bold",
    color: colors.textPrimary,
    marginBottom: 2,
  },
  priorityDetail: {
    fontSize: 9,
    color: colors.textSecondary,
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 40,
    right: 40,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  footerText: {
    fontSize: 8,
    color: colors.textTertiary,
  },
});

interface AgentBreakdown {
  agent: string;
  count: number;
  pct: number;
}

interface GscKeyword {
  term: string;
  clicks: number;
  impressions: number;
  position: number;
}

interface ClientBranding {
  clientName?: string | null;
  clientLogoUrl?: string | null;
  reportAccentColor?: string | null;
  agencyName?: string | null;
}

interface AnalyticsReportProps {
  projectName: string;
  url: string;
  date: string;
  totalGenerations: number;
  totalTokens: number;
  totalAssets: number;
  agentBreakdown: AgentBreakdown[];
  gscKeywords: GscKeyword[];
  contentVelocity: { week: string; count: number }[];
  branding?: ClientBranding;
}

export function AnalyticsReportDocument({
  projectName,
  url,
  date,
  totalGenerations,
  totalTokens,
  totalAssets,
  agentBreakdown,
  gscKeywords,
  contentVelocity,
  branding,
}: AnalyticsReportProps) {
  const accentColor = branding?.reportAccentColor || colors.accent;
  const preparedBy = branding?.agencyName
    ? `Prepared by ${branding.agencyName} using Conduikt`
    : "Generated by Conduikt";

  return (
    <Document>
      {/* Cover Page */}
      <Page size="A4" style={styles.coverPage}>
        {branding?.clientLogoUrl ? (
          <Image
            src={branding.clientLogoUrl}
            style={{ width: 120, height: 48, objectFit: "contain", marginBottom: 40 }}
          />
        ) : (
          <View style={[styles.brandMark, { backgroundColor: accentColor }]}>
            <Text style={styles.brandLetter}>C</Text>
          </View>
        )}
        <Text style={styles.coverTitle}>Analytics Report</Text>
        <Text style={styles.coverSubtitle}>
          {branding?.clientName || projectName}
        </Text>

        <View style={styles.metaRow}>
          <Text style={styles.metaLabel}>Website</Text>
          <Text style={styles.metaValue}>{url}</Text>
        </View>
        <View style={styles.metaRow}>
          <Text style={styles.metaLabel}>Report Date</Text>
          <Text style={styles.metaValue}>{date}</Text>
        </View>
        <View style={styles.metaRow}>
          <Text style={styles.metaLabel}>Total Generations</Text>
          <Text style={styles.metaValue}>{totalGenerations}</Text>
        </View>

        <View style={styles.footer}>
          <Text style={styles.footerText}>{preparedBy}</Text>
          <Text style={styles.footerText}>conduikt.com</Text>
        </View>
      </Page>

      {/* Summary Page */}
      <Page size="A4" style={styles.page}>
        <Text style={[styles.sectionTitle, { color: accentColor }]}>
          Content Summary
        </Text>

        <View style={styles.statRow}>
          <View style={styles.statCard}>
            <Text style={styles.statLabel}>Generations</Text>
            <Text style={styles.statValue}>{totalGenerations}</Text>
          </View>
          <View style={styles.statCard}>
            <Text style={styles.statLabel}>Total Tokens</Text>
            <Text style={styles.statValue}>
              {totalTokens > 1000 ? `${(totalTokens / 1000).toFixed(1)}k` : totalTokens}
            </Text>
          </View>
          <View style={styles.statCard}>
            <Text style={styles.statLabel}>Saved Assets</Text>
            <Text style={styles.statValue}>{totalAssets}</Text>
          </View>
        </View>

        {/* Agent Breakdown */}
        {agentBreakdown.length > 0 && (
          <>
            <Text style={[styles.sectionTitle, { color: accentColor }]}>
              Agent Usage Breakdown
            </Text>
            <View style={styles.tableHeader}>
              <Text style={[styles.tableHeaderCell, { width: "50%" }]}>Agent</Text>
              <Text style={[styles.tableHeaderCell, { width: "25%" }]}>Count</Text>
              <Text style={[styles.tableHeaderCell, { width: "25%" }]}>Share</Text>
            </View>
            {agentBreakdown.map((a) => (
              <View key={a.agent} style={styles.tableRow}>
                <Text style={[styles.tableCell, { width: "50%" }]}>{a.agent}</Text>
                <Text style={[styles.tableCell, { width: "25%" }]}>{a.count}</Text>
                <Text style={[styles.tableCell, { width: "25%" }]}>{a.pct}%</Text>
              </View>
            ))}
          </>
        )}

        {/* Content Velocity */}
        {contentVelocity.length > 0 && (
          <>
            <Text style={[styles.sectionTitle, { color: accentColor, marginTop: 24 }]}>
              Content Velocity (Weekly)
            </Text>
            <View style={styles.tableHeader}>
              <Text style={[styles.tableHeaderCell, { width: "60%" }]}>Week</Text>
              <Text style={[styles.tableHeaderCell, { width: "40%" }]}>Pieces</Text>
            </View>
            {contentVelocity.map((v) => (
              <View key={v.week} style={styles.tableRow}>
                <Text style={[styles.tableCell, { width: "60%" }]}>{v.week}</Text>
                <Text style={[styles.tableCell, { width: "40%" }]}>{v.count}</Text>
              </View>
            ))}
          </>
        )}

        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>{preparedBy}</Text>
          <Text
            style={styles.footerText}
            render={({ pageNumber, totalPages }) =>
              `Page ${pageNumber} of ${totalPages}`
            }
          />
        </View>
      </Page>

      {/* GSC Keywords Page (if available) */}
      {gscKeywords.length > 0 && (
        <Page size="A4" style={styles.page}>
          <Text style={[styles.sectionTitle, { color: accentColor }]}>
            Keyword Performance (Google Search Console)
          </Text>
          <View style={styles.tableHeader}>
            <Text style={[styles.tableHeaderCell, { width: "40%" }]}>Keyword</Text>
            <Text style={[styles.tableHeaderCell, { width: "15%" }]}>Clicks</Text>
            <Text style={[styles.tableHeaderCell, { width: "20%" }]}>Impressions</Text>
            <Text style={[styles.tableHeaderCell, { width: "25%" }]}>Avg Position</Text>
          </View>
          {gscKeywords.slice(0, 20).map((kw) => (
            <View key={kw.term} style={styles.tableRow}>
              <Text style={[styles.tableCell, { width: "40%" }]}>{kw.term}</Text>
              <Text style={[styles.tableCell, { width: "15%" }]}>{kw.clicks}</Text>
              <Text style={[styles.tableCell, { width: "20%" }]}>{kw.impressions}</Text>
              <Text style={[styles.tableCell, { width: "25%" }]}>
                {kw.position.toFixed(1)}
              </Text>
            </View>
          ))}

          <View style={styles.footer} fixed>
            <Text style={styles.footerText}>{preparedBy}</Text>
            <Text
              style={styles.footerText}
              render={({ pageNumber, totalPages }) =>
                `Page ${pageNumber} of ${totalPages}`
              }
            />
          </View>
        </Page>
      )}
    </Document>
  );
}
