// next-env.d.ts is generated by `next dev` / `next build` and gitignored,
// so a fresh checkout (CI's typecheck) doesn't know static image imports
// like `import hero from "@/public/images/home/hero.webp"`. Pull in Next's
// image module declarations explicitly.
/// <reference types="next/image-types/global" />
