"use client";

// GENERATED by scripts/lucide-map.mjs — the old lucide-react icon names,
// rendered as IconPark icons in the v2 style (outline, stroke 3, round caps;
// docs/DESIGN.md §Icons). Lets every screen drop lucide-react by changing
// only its import line. New code should import IconPark names from
// ./icons instead.

import * as React from "react";
import {
  AddFour as ParkAddFour,
  AddUser as ParkAddUser,
  Aiming as ParkAiming,
  Api as ParkApi,
  ArrowLeft as ParkArrowLeft,
  ArrowRight as ParkArrowRight,
  ArrowRightUp as ParkArrowRightUp,
  Attention as ParkAttention,
  BankCard as ParkBankCard,
  Bill as ParkBill,
  BookOpen as ParkBookOpen,
  Bookmark as ParkBookmark,
  Branch as ParkBranch,
  BuildingOne as ParkBuildingOne,
  Calculator as ParkCalculator,
  Calendar as ParkCalendar,
  CalendarDot as ParkCalendarDot,
  CalendarThirty as ParkCalendarThirty,
  CalendarThirtyTwo as ParkCalendarThirtyTwo,
  Caution as ParkCaution,
  ChartHistogram as ParkChartHistogram,
  ChartHistogramTwo as ParkChartHistogramTwo,
  ChartLine as ParkChartLine,
  Check as ParkCheck,
  CheckCorrect as ParkCheckCorrect,
  CheckOne as ParkCheckOne,
  Click as ParkClick,
  Clipboard as ParkClipboard,
  Close as ParkClose,
  CloseOne as ParkCloseOne,
  Code as ParkCode,
  Comment as ParkComment,
  Compass as ParkCompass,
  Computer as ParkComputer,
  Connection as ParkConnection,
  Copy as ParkCopy,
  Crown as ParkCrown,
  Cycle as ParkCycle,
  Dashboard as ParkDashboard,
  Delete as ParkDelete,
  Dollar as ParkDollar,
  DoubleRight as ParkDoubleRight,
  Down as ParkDown,
  Download as ParkDownload,
  Drag as ParkDrag,
  Earth as ParkEarth,
  Edit as ParkEdit,
  Facebook as ParkFacebook,
  FileEditing as ParkFileEditing,
  FileSuccess as ParkFileSuccess,
  FileText as ParkFileText,
  Film as ParkFilm,
  Flag as ParkFlag,
  FolderOpen as ParkFolderOpen,
  FolderPlus as ParkFolderPlus,
  GoEnd as ParkGoEnd,
  HamburgerButton as ParkHamburgerButton,
  Heartbeat as ParkHeartbeat,
  Help as ParkHelp,
  History as ParkHistory,
  Inbox as ParkInbox,
  Info as ParkInfo,
  Iphone as ParkIphone,
  Key as ParkKey,
  Layers as ParkLayers,
  Left as ParkLeft,
  Lightning as ParkLightning,
  Like as ParkLike,
  Link as ParkLink,
  LinkTwo as ParkLinkTwo,
  ListCheckbox as ParkListCheckbox,
  ListView as ParkListView,
  Loading as ParkLoading,
  Lock as ParkLock,
  Magic as ParkMagic,
  MagicWand as ParkMagicWand,
  Mail as ParkMail,
  MapDraw as ParkMapDraw,
  Message as ParkMessage,
  Microscope as ParkMicroscope,
  More as ParkMore,
  Music as ParkMusic,
  PaperMoney as ParkPaperMoney,
  Peoples as ParkPeoples,
  Pic as ParkPic,
  Platte as ParkPlatte,
  Play as ParkPlay,
  PlayTwo as ParkPlayTwo,
  Plus as ParkPlus,
  Pound as ParkPound,
  PreviewClose as ParkPreviewClose,
  PreviewOpen as ParkPreviewOpen,
  ReduceUser as ParkReduceUser,
  Refresh as ParkRefresh,
  Remind as ParkRemind,
  Right as ParkRight,
  Robot as ParkRobot,
  Rocket as ParkRocket,
  Save as ParkSave,
  Search as ParkSearch,
  Send as ParkSend,
  SettingTwo as ParkSettingTwo,
  ShareOne as ParkShareOne,
  ShareTwo as ParkShareTwo,
  Shield as ParkShield,
  ShieldAdd as ParkShieldAdd,
  ShuffleOne as ParkShuffleOne,
  Sort as ParkSort,
  Speaker as ParkSpeaker,
  Square as ParkSquare,
  Star as ParkStar,
  SwitchButton as ParkSwitchButton,
  TagOne as ParkTagOne,
  Target as ParkTarget,
  Text as ParkText,
  ThumbsUp as ParkThumbsUp,
  Time as ParkTime,
  TrendTwo as ParkTrendTwo,
  Trophy as ParkTrophy,
  Undo as ParkUndo,
  Unlink as ParkUnlink,
  Up as ParkUp,
  Upload as ParkUpload,
  User as ParkUser,
  Video as ParkVideo,
  ViewGridDetail as ParkViewGridDetail,
  Wallet as ParkWallet,
  Write as ParkWrite,
} from "@icon-park/react";
import { cn } from "@/src/lib/utils/cn";

export interface IconProps extends Omit<React.HTMLAttributes<HTMLSpanElement>, "color"> {
  size?: number | string;
  /** Accepted for compatibility; v2 icons always use stroke 3. */
  strokeWidth?: number | string;
  fill?: string;
  color?: string;
  absoluteStrokeWidth?: boolean;
}
export type LucideIcon = React.ComponentType<IconProps>;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type ParkIcon = React.ComponentType<any>;

function park(Icon: ParkIcon, name: string): LucideIcon {
  const C = ({ className, size, strokeWidth: _sw, absoluteStrokeWidth: _a, fill, color, ...rest }: IconProps) => {
    void _sw;
    void _a;
    const sized = size != null;
    // Lucide-style sizing (h-4 w-4) sizes the wrapper; the svg fills it.
    const hasBox = /(^|\s)(h-|size-)/.test(className ?? "");
    return (
      <Icon
        theme="outline"
        size={sized ? size : "100%"}
        strokeWidth={3}
        strokeLinecap="round"
        strokeLinejoin="round"
        fill={fill && fill !== "none" ? fill : color ?? "currentColor"}
        aria-hidden={rest["aria-label"] ? undefined : true}
        className={cn("inline-flex shrink-0 items-center justify-center [&>svg]:block", !sized && !hasBox && "h-[1em] w-[1em]", className)}
        {...rest}
      />
    );
  };
  C.displayName = name;
  return C;
}

export const Activity = park(ParkHeartbeat, "Activity");
export const AlertCircle = park(ParkAttention, "AlertCircle");
export const AlertTriangle = park(ParkCaution, "AlertTriangle");
export const Archive = park(ParkInbox, "Archive");
export const ArrowLeft = park(ParkArrowLeft, "ArrowLeft");
export const ArrowRight = park(ParkArrowRight, "ArrowRight");
export const ArrowUpDown = park(ParkSort, "ArrowUpDown");
export const ArrowUpRight = park(ParkArrowRightUp, "ArrowUpRight");
export const BarChart2 = park(ParkChartHistogramTwo, "BarChart2");
export const BarChart3 = park(ParkChartHistogram, "BarChart3");
export const Bell = park(ParkRemind, "Bell");
export const BookOpen = park(ParkBookOpen, "BookOpen");
export const Bookmark = park(ParkBookmark, "Bookmark");
export const Bot = park(ParkRobot, "Bot");
export const Building2 = park(ParkBuildingOne, "Building2");
export const Calculator = park(ParkCalculator, "Calculator");
export const Calendar = park(ParkCalendar, "Calendar");
export const CalendarClock = park(ParkCalendarThirty, "CalendarClock");
export const CalendarDays = park(ParkCalendarDot, "CalendarDays");
export const CalendarPlus = park(ParkAddFour, "CalendarPlus");
export const CalendarRange = park(ParkCalendarThirtyTwo, "CalendarRange");
export const Check = park(ParkCheck, "Check");
export const CheckCheck = park(ParkDoubleRight, "CheckCheck");
export const CheckCircle2 = park(ParkCheckOne, "CheckCircle2");
export const CheckSquare = park(ParkCheckCorrect, "CheckSquare");
export const ChevronDown = park(ParkDown, "ChevronDown");
export const ChevronLeft = park(ParkLeft, "ChevronLeft");
export const ChevronRight = park(ParkRight, "ChevronRight");
export const ChevronUp = park(ParkUp, "ChevronUp");
export const ClipboardList = park(ParkClipboard, "ClipboardList");
export const Clock = park(ParkTime, "Clock");
export const Code = park(ParkCode, "Code");
export const Compass = park(ParkCompass, "Compass");
export const Copy = park(ParkCopy, "Copy");
export const CreditCard = park(ParkBankCard, "CreditCard");
export const Crosshair = park(ParkAiming, "Crosshair");
export const Crown = park(ParkCrown, "Crown");
export const DollarSign = park(ParkDollar, "DollarSign");
export const Download = park(ParkDownload, "Download");
export const ExternalLink = park(ParkShareOne, "ExternalLink");
export const Eye = park(ParkPreviewOpen, "Eye");
export const EyeOff = park(ParkPreviewClose, "EyeOff");
export const Facebook = park(ParkFacebook, "Facebook");
export const FileBarChart = park(ParkChartLine, "FileBarChart");
export const FileCheck2 = park(ParkFileSuccess, "FileCheck2");
export const FileEdit = park(ParkFileEditing, "FileEdit");
export const FileText = park(ParkFileText, "FileText");
export const Film = park(ParkFilm, "Film");
export const Flag = park(ParkFlag, "Flag");
export const FolderOpen = park(ParkFolderOpen, "FolderOpen");
export const FolderPlus = park(ParkFolderPlus, "FolderPlus");
export const GitBranch = park(ParkBranch, "GitBranch");
export const Globe = park(ParkEarth, "Globe");
export const GripVertical = park(ParkDrag, "GripVertical");
export const Hash = park(ParkPound, "Hash");
export const Heart = park(ParkLike, "Heart");
export const HelpCircle = park(ParkHelp, "HelpCircle");
export const History = park(ParkHistory, "History");
export const Image = park(ParkPic, "Image");
export const ImageIcon = park(ParkPic, "ImageIcon");
export const Inbox = park(ParkInbox, "Inbox");
export const Info = park(ParkInfo, "Info");
export const Key = park(ParkKey, "Key");
export const KeyRound = park(ParkKey, "KeyRound");
export const Layers = park(ParkLayers, "Layers");
export const LayoutDashboard = park(ParkDashboard, "LayoutDashboard");
export const LayoutGrid = park(ParkViewGridDetail, "LayoutGrid");
export const Link = park(ParkLink, "Link");
export const Link2 = park(ParkLinkTwo, "Link2");
export const List = park(ParkListView, "List");
export const ListChecks = park(ParkListCheckbox, "ListChecks");
export const Loader2 = park(ParkLoading, "Loader2");
export const Lock = park(ParkLock, "Lock");
export const Mail = park(ParkMail, "Mail");
export const Map = park(ParkMapDraw, "Map");
export const Megaphone = park(ParkSpeaker, "Megaphone");
export const Menu = park(ParkHamburgerButton, "Menu");
export const MessageCircle = park(ParkComment, "MessageCircle");
export const MessageSquare = park(ParkMessage, "MessageSquare");
export const Microscope = park(ParkMicroscope, "Microscope");
export const Monitor = park(ParkComputer, "Monitor");
export const MoreHorizontal = park(ParkMore, "MoreHorizontal");
export const MousePointerClick = park(ParkClick, "MousePointerClick");
export const Music2 = park(ParkMusic, "Music2");
export const Palette = park(ParkPlatte, "Palette");
export const PenLine = park(ParkWrite, "PenLine");
export const PenTool = park(ParkWrite, "PenTool");
export const Pencil = park(ParkEdit, "Pencil");
export const PiggyBank = park(ParkPaperMoney, "PiggyBank");
export const Play = park(ParkPlay, "Play");
export const PlaySquare = park(ParkPlayTwo, "PlaySquare");
export const Plus = park(ParkPlus, "Plus");
export const Receipt = park(ParkBill, "Receipt");
export const RefreshCw = park(ParkRefresh, "RefreshCw");
export const Repeat = park(ParkCycle, "Repeat");
export const Repeat2 = park(ParkCycle, "Repeat2");
export const Rocket = park(ParkRocket, "Rocket");
export const RotateCcw = park(ParkUndo, "RotateCcw");
export const Save = park(ParkSave, "Save");
export const Search = park(ParkSearch, "Search");
export const Send = park(ParkSend, "Send");
export const Settings = park(ParkSettingTwo, "Settings");
export const Share = park(ParkShareTwo, "Share");
export const Share2 = park(ParkShareTwo, "Share2");
export const Shield = park(ParkShield, "Shield");
export const ShieldCheck = park(ParkShieldAdd, "ShieldCheck");
export const Shuffle = park(ParkShuffleOne, "Shuffle");
export const SkipForward = park(ParkGoEnd, "SkipForward");
export const Smartphone = park(ParkIphone, "Smartphone");
export const Sparkles = park(ParkMagic, "Sparkles");
export const Square = park(ParkSquare, "Square");
export const Star = park(ParkStar, "Star");
export const Tag = park(ParkTagOne, "Tag");
export const Target = park(ParkTarget, "Target");
export const ThumbsUp = park(ParkThumbsUp, "ThumbsUp");
export const ToggleLeft = park(ParkSwitchButton, "ToggleLeft");
export const ToggleRight = park(ParkSwitchButton, "ToggleRight");
export const Trash2 = park(ParkDelete, "Trash2");
export const TrendingUp = park(ParkTrendTwo, "TrendingUp");
export const Trophy = park(ParkTrophy, "Trophy");
export const Type = park(ParkText, "Type");
export const Unlink = park(ParkUnlink, "Unlink");
export const Upload = park(ParkUpload, "Upload");
export const User = park(ParkUser, "User");
export const UserMinus = park(ParkReduceUser, "UserMinus");
export const UserPlus = park(ParkAddUser, "UserPlus");
export const Users = park(ParkPeoples, "Users");
export const Video = park(ParkVideo, "Video");
export const Wallet = park(ParkWallet, "Wallet");
export const Wand2 = park(ParkMagicWand, "Wand2");
export const Webhook = park(ParkApi, "Webhook");
export const Workflow = park(ParkConnection, "Workflow");
export const X = park(ParkClose, "X");
export const XCircle = park(ParkCloseOne, "XCircle");
export const Zap = park(ParkLightning, "Zap");

// Brand marks IconPark doesn't carry (LinkedIn) or carries in an outdated
// form (the Twitter bird; X uses its own mark now).
function brand(name: string, path: string): LucideIcon {
  const C = ({ className, size, fill, color, strokeWidth: _sw, absoluteStrokeWidth: _a, ...rest }: IconProps) => {
    void _sw;
    void _a;
    const hasBox = /(^|\s)(h-|size-)/.test(className ?? "");
    return (
      <span
        aria-hidden={rest["aria-label"] ? undefined : true}
        className={cn("inline-flex shrink-0 items-center justify-center", size == null && !hasBox && "h-[1em] w-[1em]", className)}
        style={size != null ? { width: size, height: size } : undefined}
        {...rest}
      >
        <svg viewBox="0 0 24 24" width="100%" height="100%" fill={fill && fill !== "none" ? fill : color ?? "currentColor"} aria-hidden>
          <path d={path} />
        </svg>
      </span>
    );
  };
  C.displayName = name;
  return C;
}

export const Linkedin = brand(
  "Linkedin",
  "M20.45 20.45h-3.56v-5.57c0-1.33-.02-3.04-1.85-3.04-1.86 0-2.14 1.45-2.14 2.95v5.66H9.34V9h3.42v1.56h.05c.48-.9 1.64-1.85 3.37-1.85 3.6 0 4.27 2.37 4.27 5.46v6.28zM5.34 7.43a2.06 2.06 0 1 1 0-4.13 2.06 2.06 0 0 1 0 4.13zM7.12 20.45H3.56V9h3.56v11.45zM22.22 0H1.77C.79 0 0 .77 0 1.73v20.54C0 23.23.79 24 1.77 24h20.45c.98 0 1.78-.77 1.78-1.73V1.73C24 .77 23.2 0 22.22 0z"
);
export const Twitter = brand(
  "Twitter",
  "M18.24 2.25h3.31l-7.23 8.26 8.5 11.24h-6.66l-5.21-6.82-5.97 6.82H1.68l7.73-8.84L1.25 2.25h6.83l4.71 6.23 5.45-6.23zm-1.16 17.52h1.83L7.08 4.13H5.12l11.96 15.64z"
);
